AllCops:
  Exclude:
    - 'vendor/**/*'
    - '36mvendo/**'
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'config/spring.rb'
    - 'config/puma.rb'
    - 'config/initializers/*.rb'
    - 'config/environments/*.rb'
    - 'config/environment.rb'
    - 'config/deploy.rb'
    - 'config/deploy/*.rb'
    - 'config/boot.rb'
    - 'config/application.rb'
    - 'bin/**'
    - 'app/services/tweet_next_ayah.rb'
    - 'Rakefile'
    - 'Guardfile'
    - 'node_modules/**/*'
Metrics/BlockLength:
  Exclude:
  - 'config/routes.rb'
  - 'spec/**/*.rb'
Documentation:
  Enabled: false